### PR TITLE
Cosmetics

### PR DESCRIPTION
**Pull request by gwarf**
Cosmetics fixes, should trigger first run of the GitHub Actions workflows.

### CODE REVIEW

**Comment by gwarf** [comment]
@glarocca I fixed the formatting and also a link that was identified as broken by the markdown-link-check, but there is still one link that is problematic:
https://old.astron.nl/radio-observatory/lofar-science/lofar-papers/lofar-papers
Screenshot 2020-11-16 at 10 36 06

I tried to change the URL by removing the `.old` part of the domain, but it's even worst:

Screenshot 2020-11-16 at 10 39 38

I'm not sure if it makes sense to publish such as URL that is causing security problems.
If we really need I can add an exception in https://github.com/EGI-Foundation/impact-report/blob/main/mlc_config.json

What do you suggest?

**Comment by glarocca** [comment]
I suggest to change it with the following:
https://lofar-surveys.org/publications.html

**Comment by gwarf** [comment]
> I suggest to change it with the following:
> https://lofar-surveys.org/publications.html

Done, the PR is ready for your review now :)

**Review by glarocca — APPROVED** [review]
Approve this review. Thank you Baptiste! ;)

**Pull request merged**
